name: bama
description: "במה – ניהול רשימות שירים והצגת אקורדים להופעות"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.13.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  file_picker: ^10.3.3
  syncfusion_flutter_pdf: ^34.2.7
  flutter_svg: ^2.3.0
  tesseract_ocr: ^0.5.0
  pdfx: ^2.11.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/tessdata_config.json
    - assets/tessdata/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: assets/logo.png
  min_sdk_android: 21
